<?php

namespace Actions;

use App\Models\Products;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;
use function route;

class ProductStatusTest extends TestCase
{
    use RefreshDatabase;
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->artisan('db:seed --class=SeederTablaPermisos');
    }

    public function test_it_can_change_product_status_to_desabled(): void
    {
        $product = Products::factory()->create();
        $user = User::factory()->create()->givePermissionTo('editar-producto');
        $response = $this->actingAs($user)->put(route('productStatus',$product->id));
        $response->assertRedirect();

    }

    public function test_it_can_change_product_status_to_enabled(): void
    {
        $product = Products::factory()->create();
        $user = User::factory()->create()->givePermissionTo('editar-producto');
        $this->actingAs($user)->put(route('productStatus',$product->id));
        $response = $this->actingAs($user)->put(route('productStatus',$product->id));
        $response->assertRedirect();

    }
}
