<?php

namespace Tests\Feature\Admin\Users;

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class IndexUserTest extends TestCase
{
    use RefreshDatabase;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->artisan('db:seed --class=SeederTablaPermisos');
    }

    public function test_it_can_list_users(): void
    {
        $user = User::factory()->create()->givePermissionTo('ver-usuario');
        $response = $this->actingAs($user)->get(route('usuarios.index'));
        $response->assertStatus(200);
        $response->assertViewIs('usuarios.index');
        $response->assertViewHas('usuarios');
    }

    public function test_it_user_doesnt_permissions_cant_list_users(): void
    {
        $user2 = User::factory()->create();
        $response = $this->actingAs($user2)->get(route('usuarios.index'));
        $response->assertForbidden();
    }
}
