<?php

namespace Tests\Feature\Admin\Products;

use App\Models\Products;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Http\UploadedFile;
use Tests\TestCase;

class DestroyProductTest extends TestCase
{
    use RefreshDatabase;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->artisan('db:seed --class=SeederTablaPermisos');
    }
    public function test_it_can_delete_products(): void
    {
        $data = Products::factory()->create();
        $user = User::factory()->create()->givePermissionTo('borrar-producto');
        $response = $this->actingAs($user)->delete("/productos/{$data->id}");
        $response->assertRedirect();
    }
}
