<?php

namespace Tests\Feature\Products;

use App\Models\Category;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Arr;
use Tests\TestCase;


class StoreProductTest extends TestCase
{
    use RefreshDatabase;
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->artisan('db:seed --class=SeederTablaPermisos');
    }

    public function test_it_stores_a_new_product(): void
    {
        Category::create([
            'name' => 'ordenadores',
            'description' => 'esto es un test'
        ]);
        $data= [
            'name' => 'Test product',
            'price' => 100,
            'description' => 'I am a test product',
            'storage' => '500 GB',
            'stock' => '150',
            'ram' => '16',
            'processor' => 'AMD Ryzen 5',
            'graph' => '1660 TI',
            'brand' => 'Asus',
            'category_id' => '1',
            'image' => UploadedFile::fake()->image('product.jpg', 500, 250)->size(50),
        ];
        $user = User::factory()->create()->givePermissionTo('crear-producto');
        $response = $this->actingAs($user)->post(route('productos.store'), $data);
        $response->assertSessionHasNoErrors();
        $response->assertRedirect();
    }

}
